---
# Source: sd-core/charts/5g-control-plane/templates/configmap-amf.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: amf
  labels:
    release: sd-core
    app: amf
data:
  amf-run.sh: |
    #!/bin/sh
    
    # Copyright 2020-present Open Networking Foundation
    #
    # SPDX-License-Identifier: Apache-2.0
    
    set -xe
    
    IMGPATH=/free5gc
    
    cd $IMGPATH
    cat config/amfcfg.conf
    
    GOTRACEBACK=crash ./amf/amf -amfcfg config/amfcfg.conf
    
  amfcfg.conf: |-
    configuration:
      amfName: AMF
      networkFeatureSupport5GS:
        emc: 0
        emcN3: 0
        emf: 0
        enable: true
        imsVoPS: 0
        iwkN26: 0
        mcsi: 0
        mpsi: 0
      networkName:
        full: Aether5G
        short: Aether
      ngapIpList:
      - 0.0.0.0
      non3gppDeregistrationTimerValue: 3240
      nrfUri: http://nrf:29510
      plmnSupportList:
      - plmnId:
          mcc: "208"
          mnc: "93"
        snssaiList:
        - sd: "010203"
          sst: 1
      sbi:
        bindingIPv4: 0.0.0.0
        port: 29518
        registerIPv4: amf
        scheme: http
      security:
        cipheringOrder:
        - NEA0
        integrityOrder:
        - NIA1
        - NIA2
      servedGuamiList:
      - amfId: cafe00
        plmnId:
          mcc: "208"
          mnc: "93"
      serviceNameList:
      - namf-comm
      - namf-evts
      - namf-mt
      - namf-loc
      - namf-oam
      supportDnnList:
      - internet
      supportTaiList:
      - plmnId:
          mcc: "208"
          mnc: "93"
        tac: 1
      t3502Value: 720
      t3512Value: 3600
      t3513:
        enable: true
        expireTime: 6s
        maxRetryTimes: 4
      t3522:
        enable: true
        expireTime: 6s
        maxRetryTimes: 4
      t3550:
        enable: true
        expireTime: 6s
        maxRetryTimes: 4
      t3560:
        enable: true
        expireTime: 6s
        maxRetryTimes: 4
      t3565:
        enable: true
        expireTime: 6s
        maxRetryTimes: 4
    info:
      description: AMF initial local configuration
      version: 1.0.0
    logger:
      AMF:
        ReportCaller: false
        debugLevel: info
      AUSF:
        ReportCaller: false
        debugLevel: info
      Aper:
        ReportCaller: false
        debugLevel: info
      CommonConsumerTest:
        ReportCaller: false
        debugLevel: info
      FSM:
        ReportCaller: false
        debugLevel: info
      MongoDBLibrary:
        ReportCaller: false
        debugLevel: info
      N3IWF:
        ReportCaller: false
        debugLevel: info
      NAS:
        ReportCaller: false
        debugLevel: info
      NGAP:
        ReportCaller: false
        debugLevel: info
      NRF:
        ReportCaller: false
        debugLevel: info
      NamfComm:
        ReportCaller: false
        debugLevel: info
      NamfEventExposure:
        ReportCaller: false
        debugLevel: info
      NsmfPDUSession:
        ReportCaller: false
        debugLevel: info
      NudrDataRepository:
        ReportCaller: false
        debugLevel: info
      OpenApi:
        ReportCaller: false
        debugLevel: info
      PCF:
        ReportCaller: false
        debugLevel: info
      PFCP:
        ReportCaller: false
        debugLevel: info
      PathUtil:
        ReportCaller: false
        debugLevel: info
      SMF:
        ReportCaller: false
        debugLevel: info
      UDM:
        ReportCaller: false
        debugLevel: info
      UDR:
        ReportCaller: false
        debugLevel: info
      WEBUI:
        ReportCaller: false
        debugLevel: info
---
# Source: sd-core/charts/5g-control-plane/templates/service-amf.yaml
apiVersion: v1
kind: Service
metadata:
  name: amf
  labels:
    release: sd-core
    app: amf
spec:
  type: ClusterIP
  selector:
    release: sd-core
    app: amf
  ports:
  - name: prometheus-exporter
    port: 9089
    protocol: TCP
  - name: sbi
    port: 29518
    protocol: TCP
  - name: ngapp
    port: 38412
    protocol: SCTP
---
# Source: sd-core/charts/5g-control-plane/templates/deployment-amf.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amf
  namespace: omec
  labels:
    release: sd-core
    app: amf
---
# Source: sd-core/charts/5g-control-plane/templates/deployment-amf.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: amf
  namespace: omec
  labels:
    release: sd-core
    app: amf
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
      - patch
    resources:
      - statefulsets
      - daemonsets
      - jobs
      - pods
      - services
      - endpoints
      - configmaps
---
# Source: sd-core/charts/5g-control-plane/templates/deployment-amf.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: amf
  namespace: omec
  labels:
    release: sd-core
    app: amf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: amf
subjects:
  - kind: ServiceAccount
    name: amf
    namespace: omec
---
# Source: sd-core/charts/5g-control-plane/templates/deployment-amf.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf
  labels:
    release: sd-core
    app: amf
spec:
  replicas: 1
  #serviceName: amf-headless
  selector:
    matchLabels:
      release: sd-core
      app: amf
  template:
    metadata:
      labels:
        release: sd-core
        app: amf
      annotations:
        field.cattle.io/workloadMetrics: '[{"path":"/metrics","port":9089,"schema":"HTTP"}]'
    spec:
      serviceAccountName: amf
      initContainers:
      - name: wait-nrf-module
        image: registry.opennetworking.org/docker.io/omecproject/pod-init:1.0.0
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nslookup nrf; do echo waiting for nrf; sleep 4; done;']
      containers:
      - name: amf
        image: registry.opennetworking.org/docker.io/omecproject/5gc-amf:master-1438b55
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        command: [ /free5gc/script/amf-run.sh ]
        env:
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: "99"
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: "info"
        - name: GRPC_TRACE
          value: "all"
        - name: GRPC_VERBOSITY
          value: "debug"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MANAGED_BY_CONFIG_POD 
          value: "true"
        volumeMounts:
        - name: run-script
          mountPath: /free5gc/script/amf-run.sh
          subPath: amf-run.sh
        - name: amf-config
          mountPath: /free5gc/config
      volumes:
      - name: run-script
        configMap:
          name: amf
          defaultMode: 493
      - name: amf-config
        configMap:
          name: amf
          defaultMode: 493
