---
# Source: sd-core/charts/omec-user-plane/templates/service-upf.yaml
apiVersion: v1
kind: Service
metadata:
  name: exitlb
  labels:
    release: sd-core
    app: exitlb
spec:
  type: ClusterIP
  selector:
    release: sd-core
    app: exitlb
  ports:
  - name: exitlb-web
    protocol: TCP
    port: 8080
---
# Source: sd-core/charts/omec-user-plane/templates/statefulset-upf.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: exitlb
  labels:
    release: sd-core
    app: exitlb
spec:
  replicas: 1
  serviceName: exitlb-headless
  selector:
    matchLabels:
      release: sd-core
      app: exitlb
  template:
    metadata:
      labels:
        release: sd-core
        app: exitlb
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name": "exitlb-net",
            "interface": "core",
            "ips": ["192.168.254.2/24"]
          },
          {
            "name": "core-upf1-net",
            "interface": "upf101",
            "ips": ["192.168.250.101/32"]
          },
          {
            "name": "core-upf2-net",
            "interface": "upf102",
            "ips": ["192.168.250.102/32"]
          },
          {
            "name": "core-upf3-net",
            "interface": "upf103",
            "ips": ["192.168.250.103/32"]
          }
        ]'
    spec:
      shareProcessNamespace: true
      imagePullSecrets:
        - name: aether.registry
      containers:
      - name: pfcp-agent
        image: "parhamds/exitlb:v0.0.14"
        imagePullPolicy: "IfNotPresent"
        securityContext:
          privileged: true
          runAsUser: 0
        stdin: true
        tty: true
        command: ["sh", "-xec"]
        args:
        - echo 1 > /proc/sys/net/ipv4/ip_forward;
          ip route replace default via 192.168.254.1 metric 110;
          iptables -F;
          arptables -A INPUT -s 192.168.250.3 -j DROP;
          arptables -A INPUT -s 192.168.252.3 -j DROP;
          echo 101 lb-upf1 >> /etc/iproute2/rt_tables;
          echo 102 lb-upf2 >> /etc/iproute2/rt_tables;
          echo 103 lb-upf3 >> /etc/iproute2/rt_tables;
          ip rule add fwmark 101 table lb-upf1;
          ip rule add fwmark 102 table lb-upf2;
          ip rule add fwmark 103 table lb-upf3;
          ip route add 172.250.0.0/16 dev upf101 table lb-upf1;
          ip route add 172.250.0.0/16 dev upf102 table lb-upf2;
          ip route add 172.250.0.0/16 dev upf103 table lb-upf3;
          ip route add 192.168.250.3 dev upf101 table lb-upf1;
          ip route add 192.168.250.3 dev upf102 table lb-upf2;
          ip route add 192.168.250.3 dev upf103 table lb-upf3;
          ./exitlb;