---
# Source: sd-core/charts/omec-user-plane/templates/configmap-upf.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: upf
  labels:
    release: sd-core
    app: upf
data:
  upf.json: "{\"max_sessions_threshold\":2,\"min_sessions_threshold\":2,\"max_sessions_tolerance\":0.5,\"min_sessions_tolerance\":0.1,\"reconciliation_interval\":10,\"auto_scale_out\":true,\"auto_scale_in\":true,\"max_upfs\":3,\"min_upfs\":2,\"access\":{\"ifname\":\"access\"},\"core\":{\"ifname\":\"core\"},\"cpiface\":{\"dnn\":\"internet\",\"hostname\":\"upf\",\"http_port\":\"8080\"},\"enable_notify_bess\":true,\"gtppsc\":true,\"hwcksum\":true,\"log_level\":\"trace\",\"max_sessions\":50000,\"measure_flow\":false,\"measure_upf\":true,\"mode\":\"af_packet\",\"notify_sockaddr\":\"/pod-share/notifycp\",\"qci_qos_config\":[{\"burst_duration_ms\":10,\"cbs\":50000,\"ebs\":50000,\"pbs\":50000,\"priority\":7,\"qci\":0}],\"slice_rate_limit_config\":{\"n3_bps\":1000000000,\"n3_burst_bytes\":12500000,\"n6_bps\":1000000000,\"n6_burst_bytes\":12500000},\"table_sizes\":{\"appQERLookup\":200000,\"farLookup\":150000,\"pdrLookup\":50000,\"sessionQERLookup\":100000},\"workers\":1}"
---
# Source: sd-core/charts/omec-user-plane/templates/service-upf.yaml
apiVersion: v1
kind: Service
metadata:
  name: upf
  labels:
    release: sd-core
    app: upf
spec:
  type: ClusterIP
  selector:
    release: sd-core
    app: upf
  ports:
  - name: pfcp
    protocol: UDP
    port: 8805
  - name: pfcp-down
    protocol: UDP
    port: 8806
---
# Source: sd-core/charts/omec-user-plane/templates/service-upf.yaml
apiVersion: v1
kind: Service
metadata:
  name: upf-http
  labels:
    release: sd-core
    app: upf
spec:
  type: ClusterIP
  selector:
    release: sd-core
    app: upf
  ports:
  - name: bess-web
    protocol: TCP
    port: 8000
  - name: prometheus-exporter
    protocol: TCP
    port: 8080
  - name: prometheus-exporter-down
    protocol: TCP
    port: 8081
---
# Source: sd-core/charts/5g-control-plane/templates/deployment-amf.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: upf
  namespace: omec
  labels:
    release: sd-core
    app: upf
---
# Source: sd-core/charts/5g-control-plane/templates/deployment-amf.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: upf
  namespace: omec
  labels:
    release: sd-core
    app: upf
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
      - patch
      - create
      - delete
    resources:
      - statefulsets
      - daemonsets
      - jobs
      - pods
      - services
      - endpoints
      - configmaps
---
# Source: sd-core/charts/5g-control-plane/templates/deployment-amf.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: upf
  namespace: omec
  labels:
    release: sd-core
    app: upf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: upf
subjects:
  - kind: ServiceAccount
    name: upf
    namespace: omec
---
# Source: sd-core/charts/omec-user-plane/templates/statefulset-upf.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: upf
  labels:
    release: sd-core
    app: upf
spec:
  replicas: 1
  serviceName: upf-headless
  selector:
    matchLabels:
      release: sd-core
      app: upf
  template:
    metadata:
      labels:
        release: sd-core
        app: upf
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name": "access-net",
            "interface": "access",
            "ips": ["192.168.252.61/24"]
          },
          {
            "name": "core-net",
            "interface": "core",
            "ips": ["192.168.250.61/24"]
          }
        ]'
    spec:
      serviceAccountName: upf
      shareProcessNamespace: true
      imagePullSecrets:
        - name: aether.registry
      containers:
      - name: pfcp-agent
        image: "parhamds/upf-scaler-pfcpiface:v0.2.02"
        imagePullPolicy: "IfNotPresent"
        command: ["pfcpiface"]
        args:
          - -config
          - /tmp/conf/upf.json
        volumeMounts:
          - name: shared-app
            mountPath: /pod-share
          - name: configs
            mountPath: /tmp/conf
      volumes:
      - name: configs
        configMap:
          name: upf
          defaultMode: 493
      - name: shared-app
        emptyDir: {}
